let intput_field = document.getElementById("inputEcriture");
let validation_button = document.getElementById("btnValiderMot");
let to_type_word = document.querySelector(".zoneProposition");
let score = document.querySelector(".zoneScore span");
let button_list = document.querySelectorAll(".zoneOptions input");
console.log(intput_field);
console.log(validation_button);
console.log(to_type_word);
console.log(score);
console.log(button_list);