version: '3.8'

services:

  database:
    container_name: database
    ports:
      - 5434:5432
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_volume:/var/lib/postgresql/data
    networks:
      transcendance:
networks:
  transcendance:
