import monstera from '../assets/monstera.jpg'
export const plantList = [
	{
		name: 'monstera',
		category: 'classique',
		id: '1ed',
		isBestSale: true,
		water: 3,
		light: 2,
		cover: monstera,
		price: 7,
	},
	{
		name: 'ficus lyrata',
		category: 'classique',
		id: '2ab',
		isBestSale: true,
		water: 3,
		light: 3,
		cover: monstera,
		price: 15,
	},
	{
		name: 'pothos argenté',
		category: 'classique',
		id: '3sd',
		isBestSale: false,
		isSpecialOffer: true,
		water: 3,
		light: 2,
		price: 3,
		cover: monstera,
	},
	{
		name: 'yucca',
		category: 'classique',
		id: '4kk',
		isBestSale: true,
		water: 3,
		light: 1,
		cover: monstera,
		price: 7,
	},
	{
		name: 'olivier',
		category: 'extérieur',
		id: '5pl',
		isBestSale: true,
		isSpecialOffer: true,
		water: 1,
		light: 2,
		cover: monstera,
		price: 2,
	},
	{
		name: 'géranium',
		category: 'extérieur',
		id: '6uo',
		isBestSale: false,
		isSpecialOffer: true,
		water: 3,
		light: 2,
		cover: monstera,
		price: 8,
	},
	{
		name: 'basilique',
		category: 'extérieur',
		id: '7ie',
		isBestSale: true,
		water: 1,
		light: 2,
		cover: monstera,
		price: 12,
	},
	{
		name: 'aloe',
		category: 'plante grasse',
		id: '8fp',
		isBestSale: true,
		water: 3,
		light: 2,
		cover: monstera,
		price: 4,
	},
	{
		name: 'succulente',
		category: 'plante grasse',
		id: '9vn',
		isBestSale: false,
		isSpecialOffer: true,
		water: 0,
		light: 3,
		cover: monstera,
		price: 8,
	}
]